name: SlashMe
version: 1.2
main: net.sneakymouse.slashme.SlashMe
description: A plugin for Minecraft Paper that allowes users to express their /me messages on their characters bodies by using TextDisplay entities
authors: [Team Sneakymouse, Momo the Bard, Bungo]
website: https://github.com/Team-Sneakymouse/SlashMe-Paper
api-version: "1.19"

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: true
    CoreProtect:
      load: BEFORE
      required: false